from double_stack import DoubleStack

# reverser = StringReverser()
# print(reverser.reverse("Hello World!"))
#
# expression = Expression()
# print(expression.is_balance('('))
# print(expression.is_balance('(()'))
# print(expression.is_balance(')('))
# print(expression.is_balance('()'))
# print(expression.is_balance('{123]'))
# print(expression.is_balance('{123}'))

# stack = Stack(5)
# print(stack.peek())
# stack.push(1)
# stack.push(2)
# stack.push(3)
# stack.pop()
# stack.pop()
# stack.pop()
# print(stack.is_empty())

double_stack = DoubleStack(5)
double_stack.push_first(1)
double_stack.push_first(2)
double_stack.push_first(3)
double_stack.push_second(4)
double_stack.push_second(5)
double_stack.pop_first()
double_stack.pop_first()
double_stack.pop_first()
double_stack.pop_second()
double_stack.pop_second()
print(double_stack)
